steps:
  - id: unshallow
    name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']

  - id: diff
    name: gcr.io/cloud-builders/git
    args: ['diff', 'origin/${_BASE_BRANCH}..origin/${_HEAD_BRANCH}', '> _changed_files']

  - id: pytest
    name: python:slim
    script: | 
      pip install -r requirements.txt

      echo "Files changed in PR $_PR_NUMBER (origin/${_BASE_BRANCH}..origin/${_HEAD_BRANCH}):"
      cat _changed_files

      # do stuff. 