steps: 

  - name: "ubuntu"
    entrypoint: /bin/bash
    args: 
      - -c
      - | 
        echo "Identification step"
        env

  - name: "ubuntu"
    args: ["env"]

  - name: "ubuntu"
    script: | 
      #!/bin/bash
      echo "pwd: $(pwd)"
      echo "Directory Listing"
      ls
      echo "\nDirectory Listing (with hidden files)"
      ls -la

      #git status


  
  - name: "ubuntu"
    script: | 
      #!/bin/bash

      for i in $(ls -d */); do
        ls $i
      done