steps:
  - id: unshallow
    name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']

  - id: diff
    name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - |
        git diff origin/${_BASE_BRANCH}..origin/${_HEAD_BRANCH} --name-only > _changed_files

  - id: process
    name: ubuntu
    script: |
      #!bin/bash
      CHANGED_FOLDERS=$(cat _changed_files  | cut -d '/' -f1 | sort | uniq | tr '\n' ' ')

      echo "Changed files:"
      echo $CHANGED_FILES
      echo ""
      echo "Changed folders:"
      echo $CHANGED_FOLDERS

      echo CHANGED_FOLDERS > _changed_folders

# Now, do the work: 

  - id: pip install
    name: python:slim
    entrypoint: python
    args: ["-m", "pip", "install", "-r", "requirements.txt"]

  - id: pytest
    name: python:slim
    script: |
      #!/bin/bash
      python -m pytest $(echo _changed_folders)