steps:
  - id: "env-list"
    name: "ubuntu"
    args: ["env"]

  - id: "check substitutions"
    name: "ubuntu"
    entrypoint: "/bin/bash"
    args:
      - -c
      - |
        echo "Default substitutions"
        echo "PROJECT_ID: $PROJECT_ID"
        echo "PROJECT_NUMBER: $PROJECT_NUMBER"
        echo "BUILD_ID: $BUILD_ID"
        echo "LOCATION: $LOCATION"

        echo ""
        echo "Trigger substitutions"
        echo "TRIGGER_NAME: $TRIGGER_NAME"
        echo "COMMIT_SHA: $COMMIT_SHA"
        echo "REVISION_ID: $REVISION_ID"
        echo "REPO_NAME: $REPO_NAME"
        echo ""
        echo "BRANCH_NAME: $BRANCH_NAME"
        echo "TAG_NAME: $TAG_NAME"
        echo "REF_NAME: $REF_NAME"
        echo "TRIGGER_BUILD_CONFIG_PATH: $TRIGGER_BUILD_CONFIG_PATH"


        echo ""
        echo "GitHub-specific substitutions"
        echo "_HEAD_BRANCH: $_HEAD_BRANCH"
        echo "_BASE_BRANCH: $_BASE_BRANCH"
        echo "_HEAD_REPO_URL: $_HEAD_REPO_URL"
        echo "_PR_NUMBER: $_PR_NUMBER"


  - id: unshallow
    name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']

  - id: diff
    name: gcr.io/cloud-builders/git
    args: ['diff', 'origin/${_MAIN_BRANCH_NAME}..origin${BRANCH_NAME}']

substitutions:
  _MAIN_BRANCH_NAME: latest