steps: 

  - name: "ubuntu"
    entrypoint: /bin/bash
    args: 
      - -c
      - | 
        echo "Identification step"
        env

  - name: "ubuntu"
    args: ["env"]

  - name: "ubuntu"
    entrypoint: /bin/bash
    script: | 
      pwd
      ls
      git status


  
  - name: "ubuntu"
    script: | 
      #!/bin/bash

      for i in $(ls -d */); do
        ls $i
      done