steps:
  - id: unshallow
    name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']

  - id: diff
    name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - |
        git diff origin/${_BASE_BRANCH}..origin/${_HEAD_BRANCH} > _changed_files

  - id: pytest
    name: python:slim
    env:
      - PR_NUMBER=${_PR_NUMBER}
      - BASE_BRANCH=${_BASE_BRANCH}
      - HEAD_BRANCH=${_HEAD_BRANCH}
    script: |
      pip install -r requirements.txt

      echo "Files changed in PR $PR_NUMBER (origin/${BASE_BRANCH}..origin/${HEAD_BRANCH}):"
      cat _changed_files

      CHANGED_FOLDERS=$(git diff latest..try-tests --name-only | cut -d '/' -f1 | sort | uniq | tr '\n' ' ')

      echo "Going to run: pytest $CHANGED_FOLDERS"
      pytest $CHANGED_FOLDERS